/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ai_learning.view;

import com.ai_learning.App;
import com.ai_learning.KNN;
import com.ai_learning.NB;
import com.ai_learning.data.DataFrame;
import com.ai_learning.data.parser.Parser;
import com.ai_learning.model.validator.CrossValidator;
import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

/**
 *
 * @author natanelia
 */
public class MainPage extends javax.swing.JFrame {
    private static final int CARD_KNN = 0;
    private static final int CARD_NB = 1;
    private String method;
    private int activeCard = CARD_KNN;
    private PrintStream standardOut;
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }
    
    public class JTextAreaOutputStream extends OutputStream
    {
        private final JTextArea destination;

        public JTextAreaOutputStream (JTextArea destination)
        {
            if (destination == null)
                throw new IllegalArgumentException ("Destination is null");

            this.destination = destination;
        }

        @Override
        public void write(byte[] buffer, int offset, int length) throws IOException
        {
            final String text = new String (buffer, offset, length);
            SwingUtilities.invokeLater(new Runnable ()
                {
                    @Override
                    public void run() 
                    {
                        destination.append (text);
                    }
                });
        }

        @Override
        public void write(int b) throws IOException
        {
            write (new byte [] {(byte)b}, 0, 1);
        }
    }
    
    private void printMatrix(JTextArea area, Integer[][] matrix, ArrayList<String> classes) {
        for (int i=0; i < classes.size(); i++) {
            area.append(classes.get(i) + "\t");
        }
        area.append("\n");
        for (int i = 0; i < classes.size(); i++) {
            for (int j = 0; j < classes.size(); j++) {
                area.append(matrix[i][j].toString() + "\t");
            }
            area.append(" > should be " + classes.get(i) + "\n");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcTrain = new javax.swing.JFileChooser();
        fcTest = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        txtTrainFile = new javax.swing.JTextField();
        btnOpenFile = new javax.swing.JButton();
        cmbType = new javax.swing.JComboBox<String>();
        btnSubmit = new javax.swing.JButton();
        txtTestFile = new javax.swing.JTextField();
        btnOpenTest = new javax.swing.JButton();
        spnTarget = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        btnNB = new javax.swing.JButton();
        btnKNN = new javax.swing.JButton();
        card = new javax.swing.JPanel();
        panelKNN = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taKNN = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        panelNB = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taNB = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(628, 140));

        btnOpenFile.setText("Open...");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Full Training", "10-Fold" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnOpenTest.setText("Open...");
        btnOpenTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbType, 0, 408, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTestFile, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTrainFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrainFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTestFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenTest))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 288));

        btnNB.setText("NaiveBayes");
        btnNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNBActionPerformed(evt);
            }
        });

        btnKNN.setText("KNN");
        btnKNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKNNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNB, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(btnKNN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnKNN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        card.setLayout(new java.awt.CardLayout());

        taKNN.setColumns(20);
        taKNN.setRows(5);
        jScrollPane1.setViewportView(taKNN);

        jLabel1.setText("K");

        javax.swing.GroupLayout panelKNNLayout = new javax.swing.GroupLayout(panelKNN);
        panelKNN.setLayout(panelKNNLayout);
        panelKNNLayout.setHorizontalGroup(
            panelKNNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKNNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKNNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(panelKNNLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1)))
                .addContainerGap())
        );
        panelKNNLayout.setVerticalGroup(
            panelKNNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKNNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKNNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        card.add(panelKNN, "panelKNN");

        taNB.setColumns(20);
        taNB.setRows(5);
        jScrollPane3.setViewportView(taNB);

        javax.swing.GroupLayout panelNBLayout = new javax.swing.GroupLayout(panelNB);
        panelNB.setLayout(panelNBLayout);
        panelNBLayout.setHorizontalGroup(
            panelNBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNBLayout.setVerticalGroup(
            panelNBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        card.add(panelNB, "panelNB");

        getContentPane().add(card, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKNNActionPerformed
        ((CardLayout)card.getLayout()).show(card, "panelKNN");
        activeCard = CARD_KNN;
    }//GEN-LAST:event_btnKNNActionPerformed

    private void btnNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNBActionPerformed
        ((CardLayout)card.getLayout()).show(card, "panelNB");
        activeCard = CARD_NB;
    }//GEN-LAST:event_btnNBActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        int result = fcTrain.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fcTrain.getSelectedFile();
            txtTrainFile.setText(selectedFile.getAbsolutePath());
            
        }
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        taKNN.setText("");
        taNB.setText("");
        String algorithm = (activeCard == CARD_KNN) ? "knn" : "nb";
        String trainFile = txtTrainFile.getText();
        String testFile = txtTestFile.getText();
        int target = (int) spnTarget.getValue();
        int k = (int) jSpinner1.getValue();
        method = (String) cmbType.getSelectedItem();
        //PrintStream printStream = new PrintStream(new CustomOutputStream(taKNN));
        
        if(algorithm.equals("knn")){
            App app = new App();
            app.run(algorithm, trainFile, testFile, k, method);
            taKNN.append("Relation Name : " + app.getRelationName());
            taKNN.append("\nInstances : " + app.getInstances());
            taKNN.append("\nCorrect : " + app.getCorrect());
            taKNN.append("\n\n\nConfusion Matrix : \n\n");
            printMatrix(taKNN,app.getConfusionMatrix(),app.getTargetValues());
         
            
        }
        
        else {
            App app = new App();
            app.run(algorithm, trainFile, testFile, target, method);
            taNB.append("Relation Name : " + app.getRelationName());
            taNB.append("\nInstances : " + app.getInstances());
            taNB.append("\nCorrect : " + app.getCorrect());
            taNB.append("\n\n\nConfusion Matrix : \n\n");
            printMatrix(taNB,app.getConfusionMatrix(),app.getTargetValues());
         
        }
        
        //standardOut = System.out;
        //System.setOut(printStream);
        //System.setErr(printStream);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnOpenTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenTestActionPerformed
        int result = fcTest.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fcTest.getSelectedFile();
            txtTestFile.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnOpenTestActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKNN;
    private javax.swing.JButton btnNB;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnOpenTest;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel card;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JFileChooser fcTest;
    private javax.swing.JFileChooser fcTrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel panelKNN;
    private javax.swing.JPanel panelNB;
    private javax.swing.JSpinner spnTarget;
    private javax.swing.JTextArea taKNN;
    private javax.swing.JTextArea taNB;
    private javax.swing.JTextField txtTestFile;
    private javax.swing.JTextField txtTrainFile;
    // End of variables declaration//GEN-END:variables
}
